### ISSUE TITLE
Need to test on Linux

### ISSUE THREAD

**Issue by Jonathan50** [Jonathan50/homeed-lms#1]

**Comment by Jonathan50** [comment]
On G++ version 4.8.4 on Linux Mint I get this strange error:
`main.cpp:51:10: error: 'struct sockaddr_n' has no member named 'sin_len'`
How is that possible?

**Comment by Jonathan50** [comment]
I also had to add `#include <cstring>` (which I assume I may need to do on windows when I get round to it) and it also failed with the raw string literals.

**Comment by Jonathan50** [comment]
FJAFJKLDSKF7JKFDJ

**Comment by Jonathan50** [comment]
Yay!
Commenting out
`serv.sin_len = sizeof(serv);`
fixed it. I will delete it.
I can confirm that this successfully builds on G++ v4.8.4
:smile: :octocat: wow github emojis!
:cactus: :cake: :camel: < perl :package: :smiley:
